dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
language: node_js
node_js:
  - node # uses most recent stable node version
install:
  - npm i -g npm@5.7.1 # delete once 5.7.X is out of "pre-release"
  - npm ci             # faster, goes only from package-lock
